### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DemonRem** [EgoLeX/xpchecklistcreator#2]
Dear @EgoLeX 

I send many times a complete checklist for the boeing Dreamliner 777 , still I don't see it you mention that we have to send it to your mail I did it already and still nothing , 
by the way would you plan to release the android app source code, or do any updater that get the checklist or maybe add the app fueature that we will host our checklist in the root git "EgoLeX/xpchecklistcreator its will be very easy for everybody create their checklist without the need to you check mail each time

**Comment by EgoLeX** [comment]
Dear @DemonRem ,
thank you for your feedback. I think in the old checklist creator is the wrong email address listed. I check my email client every second day and don't see any 777 checklist inside. I will check the old email address and implement it as fast as possible. Or could you send your created checklist to my current address _akego.dev@gmail.com_ ? You can find your created checklists in the checklist creator home directory.
I'm aswell working on the feature that people won't need to send their checklist via email. But the development of this need some time because of personal difficulties.

Best regards
EgoLeX

**Comment by DemonRem** [comment]
I see ok
